/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/demo/fixtures/{fixture_name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Demo Fixture
     * @description Return a versioned, synthetic screen fixture with no provider side effects.
     */
    get: operations["getDemoFixture"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/operator/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Operator Session */
    post: operations["create_operator_session_v1_operator_session_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/webhooks/razorpay": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ingest Razorpay Webhook
     * @description Verify the untouched body and atomically enqueue provider processing.
     */
    post: operations["ingest_razorpay_webhook_v1_webhooks_razorpay_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/policy-settings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Policy Settings */
    get: operations["get_policy_settings_v1_policy_settings_get"];
    /** Update Policy Settings */
    put: operations["update_policy_settings_v1_policy_settings_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/simulations/failure-injection": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate Failure Simulation */
    post: operations["generate_failure_simulation_v1_simulations_failure_injection_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/dashboard/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Dashboard */
    get: operations["get_dashboard_v1_dashboard_metrics_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/approval-queue": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Approval Queue */
    get: operations["get_approval_queue_v1_approval_queue_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/recovery-cases": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Recovery Cases */
    get: operations["list_recovery_cases_v1_recovery_cases_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/recovery-cases/{case_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Recovery Case */
    get: operations["get_recovery_case_v1_recovery_cases__case_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/recovery-cases/{case_id}/timeline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Recovery Case Timeline */
    get: operations["get_recovery_case_timeline_v1_recovery_cases__case_id__timeline_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/recovery-cases/{case_id}/commands": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Execute Operator Command
     * @description Stable UI command façade over action-specific recovery endpoints.
     */
    post: operations["execute_operator_command_v1_recovery_cases__case_id__commands_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/recovery-cases/{case_id}/safety-dispositions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Record Safety Disposition */
    post: operations["record_safety_disposition_v1_recovery_cases__case_id__safety_dispositions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/recovery-cases/{case_id}/actions/recommend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Recommend Recovery Action */
    post: operations["recommend_recovery_action_v1_recovery_cases__case_id__actions_recommend_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/recovery-cases/{case_id}/actions/{action_id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve Recovery Action */
    post: operations["approve_recovery_action_v1_recovery_cases__case_id__actions__action_id__approve_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/recovery-cases/{case_id}/actions/{action_id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reject Recovery Action */
    post: operations["reject_recovery_action_v1_recovery_cases__case_id__actions__action_id__reject_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/recovery-cases/{case_id}/stop": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Stop Recovery Case */
    post: operations["stop_recovery_case_v1_recovery_cases__case_id__stop_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/recovery-cases/{case_id}/escalate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Escalate Recovery Case */
    post: operations["escalate_recovery_case_v1_recovery_cases__case_id__escalate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/mock/recovery-cases/{case_id}/payment-surfaces": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Open Mock Payment Surface
     * @description Explicit mock endpoint mirroring approval-triggered surface creation.
     */
    post: operations["open_mock_payment_surface_v1_mock_recovery_cases__case_id__payment_surfaces_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/mock/recovery-cases/{case_id}/payment-success": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Apply Mock Payment Success */
    post: operations["apply_mock_payment_success_v1_mock_recovery_cases__case_id__payment_success_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/lab/reports/latest": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Latest Report */
    get: operations["get_latest_report_v1_lab_reports_latest_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/lab/reports/{version}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Versioned Report */
    get: operations["get_versioned_report_v1_lab_reports__version__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/razorpay/test-onboarding/subscriptions/{subscription_id}/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sync Razorpay Test Subscription
     * @description Persist provider-owned IDs so signed webhooks can correlate safely.
     */
    post: operations["sync_razorpay_test_subscription_v1_razorpay_test_onboarding_subscriptions__subscription_id__sync_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/voice/contacts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start Voice Contact */
    post: operations["start_voice_contact_v1_voice_contacts_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/voice/cases/{case_id}/contact-setup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Configure Voice Contact */
    put: operations["configure_voice_contact_v1_voice_cases__case_id__contact_setup_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/voice/cases/{case_id}/eligibility": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Voice Eligibility */
    get: operations["voice_eligibility_v1_voice_cases__case_id__eligibility_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/voice/cases/{case_id}/timeline": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Voice Timeline */
    get: operations["voice_timeline_v1_voice_cases__case_id__timeline_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/voice/contacts/{attempt_id}/browser-transcript": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Browser Transcript */
    post: operations["browser_transcript_v1_voice_contacts__attempt_id__browser_transcript_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/voice/twiml/{attempt_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Twiml For Elevenlabs */
    post: operations["twiml_for_elevenlabs_v1_voice_twiml__attempt_id__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/voice/webhooks/twilio/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Twilio Status Webhook */
    post: operations["twilio_status_webhook_v1_voice_webhooks_twilio_status_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/voice/webhooks/elevenlabs/post-call": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Elevenlabs Post Call Webhook */
    post: operations["elevenlabs_post_call_webhook_v1_voice_webhooks_elevenlabs_post_call_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/voice/tools/elevenlabs/intent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Elevenlabs Live Intent Tool
     * @description Receive authenticated live intent tools; opt-out persists before hang-up.
     */
    post: operations["elevenlabs_live_intent_tool_v1_voice_tools_elevenlabs_intent_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/voice/intents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Supported Voice Intents */
    get: operations["supported_voice_intents_v1_voice_intents_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Root */
    get: operations["root__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ActionDecisionResponse */
    ActionDecisionResponse: {
      action: components["schemas"]["ActionResponse"];
      policy: components["schemas"]["PolicyResponse"];
    };
    /** ActionRecovery */
    ActionRecovery: {
      /** Action */
      action: string;
      /** Case Count */
      case_count: number;
      /** Treatment Recovered Count */
      treatment_recovered_count: number;
      /** Baseline Recovered Count */
      baseline_recovered_count: number;
      /** Mean Predicted Probability */
      mean_predicted_probability: number;
      /** Observed Treatment Recovery Rate */
      observed_treatment_recovery_rate: number;
      /** Simulated Incremental Recovery Paise */
      simulated_incremental_recovery_paise: number;
    };
    /** ActionResponse */
    ActionResponse: {
      /** Id */
      id: string;
      /** Case Id */
      case_id: string;
      action_type: components["schemas"]["RecoveryActionType"];
      payment_surface_type: components["schemas"]["PaymentSurfaceType"] | null;
      status: components["schemas"]["ActionStatus"];
      /** Scheduled For */
      scheduled_for: string | null;
      /** External Reference */
      external_reference: string | null;
      /** Customer Url */
      customer_url: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Completed At */
      completed_at: string | null;
    };
    /**
     * ActionStatus
     * @enum {string}
     */
    ActionStatus:
      | "PROPOSED"
      | "AWAITING_APPROVAL"
      | "SCHEDULED"
      | "EXECUTING"
      | "SUCCEEDED"
      | "FAILED"
      | "CANCELLED";
    /** ApprovalQueueItemResponse */
    ApprovalQueueItemResponse: {
      /** Case Id */
      case_id: string;
      /** Action Id */
      action_id: string;
      /** Customer Display Name */
      customer_display_name: string;
      /** Plan Name */
      plan_name: string;
      /** Amount At Risk Paise */
      amount_at_risk_paise: number;
      recommended_action: components["schemas"]["RecoveryActionType"];
      payment_surface_type: components["schemas"]["PaymentSurfaceType"] | null;
      /** Policy Reason */
      policy_reason: string;
      /**
       * Deadline
       * Format: date-time
       */
      deadline: string;
      evidence_kind: components["schemas"]["EvidenceKind"];
      /**
       * Provider
       * @enum {string}
       */
      provider: "RAZORPAY_TEST" | "RECOVERYOS";
    };
    /** ApprovalQueueResponse */
    ApprovalQueueResponse: {
      /** Items */
      items: components["schemas"]["ApprovalQueueItemResponse"][];
    };
    /** ArtifactMetadata */
    ArtifactMetadata: {
      /** Schema Version */
      schema_version: string;
      /** Artifact Version */
      artifact_version: string;
      /** Artifact Checksum */
      artifact_checksum: string;
      /** Model Type */
      model_type: string;
      /** Feature Columns */
      feature_columns: string[];
      /** Categorical Features */
      categorical_features: string[];
      /** Training Seed */
      training_seed: number;
    };
    /** BrowserTranscriptRequest */
    BrowserTranscriptRequest: {
      /** Transcript */
      transcript: string;
      /**
       * Confidence Basis Points
       * @default 10000
       */
      confidence_basis_points: number;
    };
    /** BrowserTranscriptResponse */
    BrowserTranscriptResponse: {
      /** Detected Intent */
      detected_intent: string;
      /** Disposition */
      disposition: string;
      /** Contact Must End */
      contact_must_end: boolean;
      /** Suppression Persisted */
      suppression_persisted: boolean;
    };
    /** CalibrationBucket */
    CalibrationBucket: {
      /** Lower Bound */
      lower_bound: number;
      /** Upper Bound */
      upper_bound: number;
      /** Case Count */
      case_count: number;
      /** Mean Predicted Probability */
      mean_predicted_probability: number;
      /** Observed Recovery Rate */
      observed_recovery_rate: number;
    };
    /** CaseCommandRequest */
    CaseCommandRequest: {
      /** Reason */
      reason: string;
    };
    /** CaseDetailResponse */
    CaseDetailResponse: {
      case: components["schemas"]["RecoveryCaseResponse"];
      customer: components["schemas"]["CustomerResponse"];
      subscription: components["schemas"]["SubscriptionResponse"];
      invoice: components["schemas"]["InvoiceResponse"] | null;
      payment_failure: components["schemas"]["PaymentFailureResponse"] | null;
      latest_action: components["schemas"]["ActionResponse"] | null;
      latest_policy: components["schemas"]["PolicyResponse"] | null;
      /** Available Commands */
      available_commands: string[];
    };
    /** CaseListResponse */
    CaseListResponse: {
      /** Items */
      items: components["schemas"]["CaseSummaryResponse"][];
      page: components["schemas"]["PageResponse"];
    };
    /**
     * CaseOutcome
     * @enum {string}
     */
    CaseOutcome:
      | "OPEN"
      | "RECOVERED"
      | "PARTIALLY_RECOVERED"
      | "ESCALATED"
      | "DISPUTED"
      | "STOPPED"
      | "EXPIRED";
    /** CaseSummaryResponse */
    CaseSummaryResponse: {
      /** Id */
      id: string;
      /** Merchant Id */
      merchant_id: string;
      /** Failed Invoice Id */
      failed_invoice_id: string | null;
      /** Billing Cycle Key */
      billing_cycle_key: string | null;
      /** Customer Display Name */
      customer_display_name?: string | null;
      /** Plan Name */
      plan_name?: string | null;
      /** Amount At Risk Paise */
      amount_at_risk_paise: number;
      case_outcome: components["schemas"]["CaseOutcome"];
      payment_state: components["schemas"]["PaymentState"];
      subscription_state: components["schemas"]["SubscriptionState"];
      contact_disposition: components["schemas"]["ContactDisposition"];
      revenue_attribution: components["schemas"]["RevenueAttribution"];
      diagnosis: components["schemas"]["Diagnosis"];
      recommended_action?: components["schemas"]["RecoveryActionType"] | null;
      payment_surface_type?: components["schemas"]["PaymentSurfaceType"] | null;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ContactDisposition
     * @enum {string}
     */
    ContactDisposition:
      | "NOT_CONTACTED"
      | "CONTACT_SCHEDULED"
      | "NO_ANSWER"
      | "BUSY"
      | "ENGAGED"
      | "PROMISE_TO_PAY"
      | "OPTED_OUT"
      | "WRONG_PERSON"
      | "DISPUTE"
      | "ALREADY_PAID";
    /** CustomerResponse */
    CustomerResponse: {
      /** Id */
      id: string;
      /** Display Name */
      display_name: string;
      /** Preferred Language */
      preferred_language: string;
      /** Voice Consent At */
      voice_consent_at: string | null;
      /** Opted Out At */
      opted_out_at: string | null;
      /** Customer Agent Available */
      customer_agent_available: boolean;
    };
    /** DashboardMetricsResponse */
    DashboardMetricsResponse: {
      /** Revenue At Risk Paise */
      revenue_at_risk_paise: number;
      /** Verified Recovered Revenue Paise */
      verified_recovered_revenue_paise: number;
      /** Simulated Incremental Recovery Paise */
      simulated_incremental_recovery_paise: number;
      /** Net Recovered Value Paise */
      net_recovered_value_paise: number;
      /** Active Cases */
      active_cases: number;
      /** Recovered Cases */
      recovered_cases: number;
      /** Total Cases */
      total_cases: number;
      /** Recovery Rate Basis Points */
      recovery_rate_basis_points: number;
      /** Human Review Count */
      human_review_count: number;
      /** Policy Blocked Actions */
      policy_blocked_actions: number;
    };
    /** DashboardResponse */
    DashboardResponse: {
      /** @default SIMULATED */
      evidence_kind: components["schemas"]["EvidenceKind"];
      /**
       * Currency
       * @default INR
       */
      currency: string;
      metrics: components["schemas"]["DashboardMetricsResponse"];
      /** Diagnosis Distribution */
      diagnosis_distribution: components["schemas"]["DiagnosisBucketResponse"][];
      /** Recovery By Channel */
      recovery_by_channel: components["schemas"]["RecoveryChannelResponse"][];
      /** Recent Events */
      recent_events: components["schemas"]["RecentEventResponse"][];
    };
    /** DatasetSummary */
    DatasetSummary: {
      /** Generator Version */
      generator_version: string;
      /** Seed */
      seed: number;
      /** Total Case Count */
      total_case_count: number;
      /** Training Case Count */
      training_case_count: number;
      /** Calibration Case Count */
      calibration_case_count: number;
      /** Evaluation Case Count */
      evaluation_case_count: number;
      /** Cohort Design */
      cohort_design: string;
    };
    /**
     * Diagnosis
     * @enum {string}
     */
    Diagnosis:
      | "TRANSIENT_RETRYABLE"
      | "INSUFFICIENT_FUNDS"
      | "AUTHENTICATION_REQUIRED"
      | "INSTRUMENT_INVALID"
      | "MERCHANT_ERROR"
      | "RISK_OR_COMPLIANCE_BLOCK"
      | "UNKNOWN";
    /** DiagnosisBucketResponse */
    DiagnosisBucketResponse: {
      diagnosis: components["schemas"]["Diagnosis"];
      /** Case Count */
      case_count: number;
    };
    /**
     * EvidenceKind
     * @enum {string}
     */
    EvidenceKind: "SIMULATED" | "SYSTEM_DERIVED" | "RAZORPAY_TEST_VERIFIED";
    /** FailureSimulationRequest */
    FailureSimulationRequest: {
      /**
       * Scenario
       * @enum {string}
       */
      scenario:
        | "DUPLICATE_WEBHOOK"
        | "OUT_OF_ORDER_WEBHOOK"
        | "LATE_SUCCESS"
        | "CHANGED_AUTHORITATIVE_PAYMENT_STATE";
      /**
       * Seed
       * @default 20260827
       */
      seed: number;
      /**
       * Amount Paise
       * @default 149900
       */
      amount_paise: number;
      /** @default SIMULATED */
      evidence_kind: components["schemas"]["EvidenceKind"];
    };
    /** FailureSimulationResponse */
    FailureSimulationResponse: {
      /** Scenario */
      scenario: string;
      /** Seed */
      seed: number;
      /** Case Id */
      case_id: string;
      /** Payment Id */
      payment_id: string;
      /** Amount Paise */
      amount_paise: number;
      /** Deliveries */
      deliveries: components["schemas"]["SimulatedDeliveryResponse"][];
      expected_final_payment_state: components["schemas"]["PaymentState"];
      /** Expected Revenue Entries */
      expected_revenue_entries: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InvoiceResponse */
    InvoiceResponse: {
      /** Id */
      id: string;
      /** Provider Invoice Id */
      provider_invoice_id: string;
      /** Billing Cycle Key */
      billing_cycle_key: string;
      /** Amount Paise */
      amount_paise: number;
      /** Amount Paid Paise */
      amount_paid_paise: number;
      /** Currency */
      currency: string;
      /** Invoice State */
      invoice_state: string;
    };
    /** LabGuardrails */
    LabGuardrails: {
      /** Merchant Revenue Mutated */
      merchant_revenue_mutated: boolean;
      /** Production Artifact Required */
      production_artifact_required: boolean;
      /** Label */
      label: string;
    };
    /** LabReport */
    LabReport: {
      /** Schema Version */
      schema_version: string;
      /** Report Version */
      report_version: string;
      /** Generated At */
      generated_at: string;
      /** Title */
      title: string;
      /** Evidence Kind */
      evidence_kind: string;
      artifact: components["schemas"]["ArtifactMetadata"];
      dataset: components["schemas"]["DatasetSummary"];
      metrics: components["schemas"]["MetricSummary"];
      guardrails: components["schemas"]["LabGuardrails"];
    };
    /** LiveVoiceIntentRequest */
    LiveVoiceIntentRequest: {
      /** Attempt Id */
      attempt_id: string;
      /** Event Id */
      event_id?: string | null;
      /** Intent */
      intent: string;
      /** Confidence Basis Points */
      confidence_basis_points?: number | null;
    };
    /** LiveVoiceIntentResponse */
    LiveVoiceIntentResponse: {
      /**
       * Accepted
       * @default true
       * @constant
       */
      accepted: true;
      /** Duplicate */
      duplicate: boolean;
      /** Detected Intent */
      detected_intent: string;
      /** Contact Must End */
      contact_must_end: boolean;
      /** Suppression Persisted */
      suppression_persisted: boolean;
    };
    /** MetricSummary */
    MetricSummary: {
      /** Pr Auc */
      pr_auc: number;
      /** Brier Score */
      brier_score: number;
      /** Top Decile Lift */
      top_decile_lift: number;
      /** Amount Weighted Lift */
      amount_weighted_lift: number;
      /** Calibration */
      calibration: components["schemas"]["CalibrationBucket"][];
      /** Recovery By Action */
      recovery_by_action: components["schemas"]["ActionRecovery"][];
      /** Simulated Incremental Recovery Paise */
      simulated_incremental_recovery_paise: number;
    };
    /** MockPaymentSuccessRequest */
    MockPaymentSuccessRequest: {
      /** Provider Event Id */
      provider_event_id: string;
      /** Amount Paise */
      amount_paise?: number | null;
      /**
       * Subscription Reactivated
       * @default false
       */
      subscription_reactivated: boolean;
      /** Occurred At */
      occurred_at?: string | null;
    };
    /** MockPaymentSuccessResponse */
    MockPaymentSuccessResponse: {
      case: components["schemas"]["RecoveryCaseResponse"];
      /** Newly Recognized */
      newly_recognized: boolean;
    };
    /** MockPaymentSurfaceRequest */
    MockPaymentSurfaceRequest: {
      /** Action Id */
      action_id: string;
    };
    /** OperatorCommandRequest */
    OperatorCommandRequest: {
      /**
       * Command
       * @enum {string}
       */
      command: "APPROVE" | "REJECT" | "STOP" | "ESCALATE_TO_HUMAN";
      /** Action Id */
      action_id?: string | null;
    };
    /** OperatorCommandResponse */
    OperatorCommandResponse: {
      /** Command */
      command: string;
      /** Message */
      message: string;
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /**
       * Source
       * @default api
       * @constant
       */
      source: "api";
      /**
       * Status
       * @default ACCEPTED
       * @constant
       */
      status: "ACCEPTED";
    };
    /** OperatorLoginRequest */
    OperatorLoginRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** OperatorSessionResponse */
    OperatorSessionResponse: {
      /** Operator */
      operator: string;
      /** Csrf Token */
      csrf_token: string;
      /** Expires At Epoch */
      expires_at_epoch: number;
    };
    /** PageResponse */
    PageResponse: {
      /** Next Cursor */
      next_cursor: string | null;
      /** Has More */
      has_more: boolean;
      /** Limit */
      limit: number;
    };
    /** PaymentFailureResponse */
    PaymentFailureResponse: {
      /** Id */
      id: string;
      /** Provider Payment Id */
      provider_payment_id: string | null;
      /** Amount Paise */
      amount_paise: number;
      /** Currency */
      currency: string;
      payment_state: components["schemas"]["PaymentState"];
      /** Method */
      method: string | null;
      /** Error Code */
      error_code: string | null;
      /** Error Source */
      error_source: string | null;
      /** Error Step */
      error_step: string | null;
      /** Error Reason */
      error_reason: string | null;
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
    };
    /**
     * PaymentState
     * @enum {string}
     */
    PaymentState:
      "UNKNOWN" | "FAILED" | "PENDING" | "AUTHORIZED" | "CAPTURED" | "REFUNDED";
    /**
     * PaymentSurfaceType
     * @enum {string}
     */
    PaymentSurfaceType:
      | "SUBSCRIPTION_CARD_UPDATE"
      | "SUBSCRIPTION_INVOICE_LINK"
      | "STANDARD_PAYMENT_LINK";
    /**
     * PolicyDisposition
     * @enum {string}
     */
    PolicyDisposition: "ALLOW" | "BLOCK" | "DELAY" | "REQUIRE_MANUAL_APPROVAL";
    /** PolicyResponse */
    PolicyResponse: {
      /** Id */
      id: string;
      disposition: components["schemas"]["PolicyDisposition"];
      /** Decision Code */
      decision_code: string;
      /** Reason Codes */
      reason_codes: string[];
      /** Reasons */
      reasons: string[];
      /** Policy Version */
      policy_version: string;
      /** Delay Until */
      delay_until: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** PolicySettingsResponse */
    PolicySettingsResponse: {
      /** Timezone */
      timezone: string;
      /** Quiet Hours Start */
      quiet_hours_start?: string | null;
      /** Quiet Hours End */
      quiet_hours_end?: string | null;
      /** Max Contacts Per 7 Days */
      max_contacts_per_7_days?: number | null;
      /** Require Approval Above Paise */
      require_approval_above_paise?: number | null;
      /** Require Approval Actions */
      require_approval_actions?: components["schemas"]["RecoveryActionType"][];
      /** Recovery Kill Switch */
      recovery_kill_switch: boolean;
      /** Version */
      version: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** PolicySettingsUpdate */
    PolicySettingsUpdate: {
      /** Timezone */
      timezone: string;
      /** Quiet Hours Start */
      quiet_hours_start?: string | null;
      /** Quiet Hours End */
      quiet_hours_end?: string | null;
      /** Max Contacts Per 7 Days */
      max_contacts_per_7_days?: number | null;
      /** Require Approval Above Paise */
      require_approval_above_paise?: number | null;
      /** Require Approval Actions */
      require_approval_actions?: components["schemas"]["RecoveryActionType"][];
      /** Recovery Kill Switch */
      recovery_kill_switch: boolean;
    };
    /**
     * RazorpayTestSubscriptionSyncRequest
     * @description Local customer identity for a provider subscription.
     *
     *     Email and phone values are deliberately not accepted here. Provider
     *     onboarding establishes correlation only; contact consent and destinations
     *     are managed by their dedicated, authenticated flows.
     */
    RazorpayTestSubscriptionSyncRequest: {
      /** Customer External Id */
      customer_external_id: string;
      /** Customer Display Name */
      customer_display_name: string;
      /**
       * Preferred Language
       * @default en-IN
       */
      preferred_language: string;
      /**
       * Customer Agent Available
       * @default false
       */
      customer_agent_available: boolean;
    };
    /** RazorpayTestSubscriptionSyncResponse */
    RazorpayTestSubscriptionSyncResponse: {
      /**
       * Mode
       * @default razorpay_test
       */
      mode: string;
      /** Merchant Id */
      merchant_id: string;
      customer: components["schemas"]["SyncedCustomerResponse"];
      subscription: components["schemas"]["SyncedSubscriptionResponse"];
      /** Invoices */
      invoices: components["schemas"]["SyncedInvoiceResponse"][];
    };
    /** RazorpayWebhookAckResponse */
    RazorpayWebhookAckResponse: {
      /** Provider Event Id */
      provider_event_id: string;
      /** Inbox Id */
      inbox_id: string;
      /** Outbox Id */
      outbox_id: string;
      /** Accepted */
      accepted: boolean;
      /** Duplicate */
      duplicate: boolean;
      /** Acknowledge Elapsed Ms */
      acknowledge_elapsed_ms: number;
      /** Acknowledge Within Sla */
      acknowledge_within_sla: boolean;
    };
    /** RecentEventResponse */
    RecentEventResponse: {
      /** Id */
      id: string;
      /** Case Id */
      case_id: string;
      /** Event Type */
      event_type: string;
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /** Correlation Id */
      correlation_id: string;
    };
    /** RecommendActionRequest */
    RecommendActionRequest: {
      action_type?: components["schemas"]["RecoveryActionType"] | null;
      payment_surface_type?: components["schemas"]["PaymentSurfaceType"] | null;
    };
    /**
     * RecoveryActionType
     * @enum {string}
     */
    RecoveryActionType:
      | "WAIT_FOR_GATEWAY_RETRY"
      | "OPEN_CUSTOMER_PAYMENT_SURFACE"
      | "START_VOICE"
      | "SEND_TO_CUSTOMER_AGENT"
      | "ESCALATE_TO_HUMAN"
      | "STOP";
    /** RecoveryCaseResponse */
    RecoveryCaseResponse: {
      /** Id */
      id: string;
      /** Merchant Id */
      merchant_id: string;
      /** Customer Id */
      customer_id: string;
      /** Subscription Id */
      subscription_id: string;
      /** Failed Invoice Id */
      failed_invoice_id: string | null;
      /** Billing Cycle Key */
      billing_cycle_key: string | null;
      /** Failed Payment Id */
      failed_payment_id: string | null;
      case_outcome: components["schemas"]["CaseOutcome"];
      payment_state: components["schemas"]["PaymentState"];
      subscription_state: components["schemas"]["SubscriptionState"];
      contact_disposition: components["schemas"]["ContactDisposition"];
      revenue_attribution: components["schemas"]["RevenueAttribution"];
      diagnosis: components["schemas"]["Diagnosis"];
      /** Amount At Risk Paise */
      amount_at_risk_paise: number;
      /** Arrears Collected Paise */
      arrears_collected_paise: number;
      /** Case Recovered */
      case_recovered: boolean;
      /** Subscription Reactivated */
      subscription_reactivated: boolean;
      /**
       * Opened At
       * Format: date-time
       */
      opened_at: string;
      /**
       * Recovery Deadline
       * Format: date-time
       */
      recovery_deadline: string;
      /** Recovered At */
      recovered_at: string | null;
      /** Version */
      version: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** RecoveryChannelResponse */
    RecoveryChannelResponse: {
      /**
       * Channel
       * @enum {string}
       */
      channel:
        | "SUBSCRIPTION_CARD_UPDATE"
        | "SUBSCRIPTION_INVOICE_LINK"
        | "STANDARD_PAYMENT_LINK"
        | "VOICE"
        | "CUSTOMER_AGENT";
      /** Case Count */
      case_count: number;
      /** Recovered Paise */
      recovered_paise: number;
    };
    /** RejectActionRequest */
    RejectActionRequest: {
      /** Reason */
      reason: string;
    };
    /**
     * RevenueAttribution
     * @enum {string}
     */
    RevenueAttribution:
      "NONE" | "SIMULATED" | "RAZORPAY_TEST_VERIFIED" | "VERIFIED_EXTERNAL";
    /** SafetyDispositionRequest */
    SafetyDispositionRequest: {
      /**
       * Disposition
       * @enum {string}
       */
      disposition:
        | "MARK_DISPUTE"
        | "MARK_OPT_OUT"
        | "MARK_ALREADY_PAID"
        | "MARK_WRONG_PERSON"
        | "ESCALATE_TO_HUMAN";
    };
    /** SafetyDispositionResponse */
    SafetyDispositionResponse: {
      /** Disposition */
      disposition: string;
      /** Message */
      message: string;
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      case: components["schemas"]["RecoveryCaseResponse"];
      /**
       * Source
       * @default api
       * @constant
       */
      source: "api";
      /**
       * Status
       * @default ACCEPTED
       * @constant
       */
      status: "ACCEPTED";
    };
    /** SimulatedDeliveryResponse */
    SimulatedDeliveryResponse: {
      /** Delivery Id */
      delivery_id: string;
      /** Provider Event Id */
      provider_event_id: string;
      /** Event Type */
      event_type: string;
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /**
       * Delivered At
       * Format: date-time
       */
      delivered_at: string;
      observed_payment_state: components["schemas"]["PaymentState"];
      authoritative_payment_state: components["schemas"]["PaymentState"];
      evidence_kind: components["schemas"]["EvidenceKind"];
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
    };
    /** StartVoiceContactRequest */
    StartVoiceContactRequest: {
      /** Case Id */
      case_id: string;
      /** Idempotency Key */
      idempotency_key: string;
      /**
       * Max Duration Seconds
       * @default 180
       */
      max_duration_seconds: number;
    };
    /** StartVoiceContactResponse */
    StartVoiceContactResponse: {
      /** Attempt Id */
      attempt_id: string;
      /** Provider */
      provider: string;
      /**
       * Status
       * @enum {string}
       */
      status: "SUBMITTED" | "REJECTED" | "UNCERTAIN";
      /** Reason Code */
      reason_code: string;
      /** Provider Call Id */
      provider_call_id?: string | null;
      /**
       * Retry Permitted
       * @default false
       * @constant
       */
      retry_permitted: false;
    };
    /** SubscriptionResponse */
    SubscriptionResponse: {
      /** Id */
      id: string;
      /** Provider Subscription Id */
      provider_subscription_id: string;
      /** Plan Name */
      plan_name: string;
      /** Amount Paise */
      amount_paise: number;
      /** Currency */
      currency: string;
      subscription_state: components["schemas"]["SubscriptionState"];
    };
    /**
     * SubscriptionState
     * @enum {string}
     */
    SubscriptionState:
      | "UNKNOWN"
      | "CREATED"
      | "AUTHENTICATED"
      | "ACTIVE"
      | "PENDING"
      | "HALTED"
      | "PAUSED"
      | "CANCELLED"
      | "COMPLETED";
    /** SyncedCustomerResponse */
    SyncedCustomerResponse: {
      /** Id */
      id: string;
      /** External Id */
      external_id: string;
      /** Created */
      created: boolean;
    };
    /** SyncedInvoiceResponse */
    SyncedInvoiceResponse: {
      /** Id */
      id: string;
      /** Provider Invoice Id */
      provider_invoice_id: string;
      /** Billing Cycle Key */
      billing_cycle_key: string;
      /** Amount Paise */
      amount_paise: number;
      /** Amount Paid Paise */
      amount_paid_paise: number;
      /** Currency */
      currency: string;
      /** Invoice State */
      invoice_state: string;
      /** Payment Url */
      payment_url?: string | null;
      /** Created */
      created: boolean;
    };
    /** SyncedSubscriptionResponse */
    SyncedSubscriptionResponse: {
      /** Id */
      id: string;
      /** Provider Subscription Id */
      provider_subscription_id: string;
      /** Provider Plan Id */
      provider_plan_id: string;
      /** Plan Name */
      plan_name: string;
      /** Amount Paise */
      amount_paise: number;
      /** Currency */
      currency: string;
      subscription_state: components["schemas"]["SubscriptionState"];
      /** Authorization Url */
      authorization_url?: string | null;
      /** Created */
      created: boolean;
    };
    /** TimelineEventResponse */
    TimelineEventResponse: {
      /** Id */
      id: string;
      /** Case Id */
      case_id: string;
      /** Event Type */
      event_type: string;
      /** Source */
      source: string;
      evidence_kind: components["schemas"]["EvidenceKind"];
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /**
       * Recorded At
       * Format: date-time
       */
      recorded_at: string;
      /** Correlation Id */
      correlation_id: string;
    };
    /** TimelineResponse */
    TimelineResponse: {
      /** Items */
      items: components["schemas"]["TimelineEventResponse"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** VoiceAttemptResponse */
    VoiceAttemptResponse: {
      /** Id */
      id: string;
      /** Case Id */
      case_id: string;
      /** Status */
      status: string;
      /** Disposition */
      disposition: string | null;
      /** Transcript */
      transcript: string | null;
      /** Detected Intent */
      detected_intent: string | null;
      /** Confidence Basis Points */
      confidence_basis_points?: number | null;
      /** Duration Seconds */
      duration_seconds?: number | null;
      /** Disclosure Delivered At */
      disclosure_delivered_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** VoiceContactSetupRequest */
    VoiceContactSetupRequest: {
      /** Destination Token */
      destination_token: string;
      /** Preferred Language */
      preferred_language: string;
      /** Consent Granted */
      consent_granted: boolean;
    };
    /** VoiceEligibilityResponse */
    VoiceEligibilityResponse: {
      /** Case Id */
      case_id: string;
      /** Customer Id */
      customer_id: string | null;
      /** Eligible */
      eligible: boolean;
      /** Reason Code */
      reason_code: string;
      /** Destination Configured */
      destination_configured: boolean;
      /** Destination Allowlisted */
      destination_allowlisted: boolean;
      /** Consent Verified At */
      consent_verified_at: string | null;
      /** Opted Out At */
      opted_out_at: string | null;
      /** Preferred Language */
      preferred_language: string | null;
    };
    /** VoiceTimelineResponse */
    VoiceTimelineResponse: {
      /** Items */
      items: components["schemas"]["VoiceAttemptResponse"][];
    };
    /** WebhookAcceptedResponse */
    WebhookAcceptedResponse: {
      /**
       * Accepted
       * @default true
       * @constant
       */
      accepted: true;
      /** Duplicate */
      duplicate: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getDemoFixture: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        fixture_name:
          | "dashboard"
          | "case-detail"
          | "customer-agent"
          | "customer-voice"
          | "ml-lab";
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_operator_session_v1_operator_session_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OperatorLoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OperatorSessionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  ingest_razorpay_webhook_v1_webhooks_razorpay_post: {
    parameters: {
      query?: never;
      header: {
        "X-Razorpay-Signature": string;
        "X-Razorpay-Event-Id": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RazorpayWebhookAckResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_policy_settings_v1_policy_settings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PolicySettingsResponse"];
        };
      };
    };
  };
  update_policy_settings_v1_policy_settings_put: {
    parameters: {
      query?: never;
      header?: {
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path?: never;
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PolicySettingsUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PolicySettingsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  generate_failure_simulation_v1_simulations_failure_injection_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FailureSimulationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FailureSimulationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_dashboard_v1_dashboard_metrics_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DashboardResponse"];
        };
      };
    };
  };
  get_approval_queue_v1_approval_queue_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ApprovalQueueResponse"];
        };
      };
    };
  };
  list_recovery_cases_v1_recovery_cases_get: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
        case_outcome?: components["schemas"]["CaseOutcome"][] | null;
        diagnosis?: components["schemas"]["Diagnosis"][] | null;
        subscription_state?:
          components["schemas"]["SubscriptionState"][] | null;
        opened_from?: string | null;
        opened_to?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaseListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_recovery_case_v1_recovery_cases__case_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CaseDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_recovery_case_timeline_v1_recovery_cases__case_id__timeline_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        case_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TimelineResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  execute_operator_command_v1_recovery_cases__case_id__commands_post: {
    parameters: {
      query?: never;
      header?: {
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["OperatorCommandRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OperatorCommandResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  record_safety_disposition_v1_recovery_cases__case_id__safety_dispositions_post: {
    parameters: {
      query?: never;
      header?: {
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SafetyDispositionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SafetyDispositionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  recommend_recovery_action_v1_recovery_cases__case_id__actions_recommend_post: {
    parameters: {
      query?: never;
      header?: {
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecommendActionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActionDecisionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  approve_recovery_action_v1_recovery_cases__case_id__actions__action_id__approve_post: {
    parameters: {
      query?: never;
      header?: {
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path: {
        case_id: string;
        action_id: string;
      };
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reject_recovery_action_v1_recovery_cases__case_id__actions__action_id__reject_post: {
    parameters: {
      query?: never;
      header?: {
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path: {
        case_id: string;
        action_id: string;
      };
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RejectActionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  stop_recovery_case_v1_recovery_cases__case_id__stop_post: {
    parameters: {
      query?: never;
      header?: {
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CaseCommandRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecoveryCaseResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  escalate_recovery_case_v1_recovery_cases__case_id__escalate_post: {
    parameters: {
      query?: never;
      header?: {
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CaseCommandRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecoveryCaseResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  open_mock_payment_surface_v1_mock_recovery_cases__case_id__payment_surfaces_post: {
    parameters: {
      query?: never;
      header?: {
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MockPaymentSurfaceRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ActionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  apply_mock_payment_success_v1_mock_recovery_cases__case_id__payment_success_post: {
    parameters: {
      query?: never;
      header?: {
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MockPaymentSuccessRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MockPaymentSuccessResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_latest_report_v1_lab_reports_latest_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LabReport"];
        };
      };
    };
  };
  get_versioned_report_v1_lab_reports__version__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LabReport"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sync_razorpay_test_subscription_v1_razorpay_test_onboarding_subscriptions__subscription_id__sync_post: {
    parameters: {
      query?: never;
      header?: {
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path: {
        subscription_id: string;
      };
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RazorpayTestSubscriptionSyncRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RazorpayTestSubscriptionSyncResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_voice_contact_v1_voice_contacts_post: {
    parameters: {
      query?: never;
      header?: {
        "X-Recovery-Operator-Token"?: string | null;
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path?: never;
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartVoiceContactRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StartVoiceContactResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  configure_voice_contact_v1_voice_cases__case_id__contact_setup_put: {
    parameters: {
      query?: never;
      header?: {
        "X-Recovery-Operator-Token"?: string | null;
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VoiceContactSetupRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VoiceEligibilityResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  voice_eligibility_v1_voice_cases__case_id__eligibility_get: {
    parameters: {
      query?: never;
      header?: {
        "X-Recovery-Operator-Token"?: string | null;
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VoiceEligibilityResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  voice_timeline_v1_voice_cases__case_id__timeline_get: {
    parameters: {
      query?: never;
      header?: {
        "X-Recovery-Operator-Token"?: string | null;
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path: {
        case_id: string;
      };
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VoiceTimelineResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  browser_transcript_v1_voice_contacts__attempt_id__browser_transcript_post: {
    parameters: {
      query?: never;
      header: {
        "x-voice-event-id": string;
        "X-Recovery-Operator-Token"?: string | null;
        "X-RecoveryOS-Operator-Token"?: string | null;
        "X-RecoveryOS-CSRF-Token"?: string | null;
      };
      path: {
        attempt_id: string;
      };
      cookie?: {
        recoveryos_operator_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BrowserTranscriptRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BrowserTranscriptResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  twiml_for_elevenlabs_v1_voice_twiml__attempt_id__post: {
    parameters: {
      query?: never;
      header?: {
        "x-twilio-signature"?: string | null;
      };
      path: {
        attempt_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  twilio_status_webhook_v1_voice_webhooks_twilio_status_post: {
    parameters: {
      query: {
        attempt_id: string;
      };
      header?: {
        "x-twilio-signature"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WebhookAcceptedResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  elevenlabs_post_call_webhook_v1_voice_webhooks_elevenlabs_post_call_post: {
    parameters: {
      query?: never;
      header?: {
        "ElevenLabs-Signature"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WebhookAcceptedResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  elevenlabs_live_intent_tool_v1_voice_tools_elevenlabs_intent_post: {
    parameters: {
      query?: never;
      header?: {
        "X-ElevenLabs-Tool-Secret"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LiveVoiceIntentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LiveVoiceIntentResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  supported_voice_intents_v1_voice_intents_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
    };
  };
  root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string | boolean;
          };
        };
      };
    };
  };
}
