"""create core recovery schema

Revision ID: 61d778a7486b
Revises:
Create Date: 2026-08-27 20:42:07.096833
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import services.api.app.models.entities

revision: str = "61d778a7486b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "created_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint("length(currency) = 3", name=op.f("ck_merchants_currency_length")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants")),
        sa.UniqueConstraint("external_id", name=op.f("uq_merchants_external_id")),
    )
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("deduplication_key", sa.String(length=200), nullable=False),
        sa.Column(
            "available_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "published_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_outbox_messages_outbox_attempt_nonnegative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_messages")),
        sa.UniqueConstraint("deduplication_key", name=op.f("uq_outbox_messages_deduplication_key")),
    )
    op.create_index(
        op.f("ix_outbox_messages_aggregate_id"), "outbox_messages", ["aggregate_id"], unique=False
    )
    op.create_index(
        "ix_outbox_unpublished",
        "outbox_messages",
        ["published_at", "available_at", "id"],
        unique=False,
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("email_token", sa.String(length=256), nullable=True),
        sa.Column("phone_token", sa.String(length=256), nullable=True),
        sa.Column("preferred_language", sa.String(length=32), nullable=False),
        sa.Column(
            "voice_consent_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "opted_out_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("customer_agent_available", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_customers_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("merchant_id", "external_id", name="customer_merchant_external"),
    )
    op.create_index(op.f("ix_customers_merchant_id"), "customers", ["merchant_id"], unique=False)
    op.create_table(
        "webhook_inbox",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_event_id", sa.String(length=200), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "received_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "processed_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("processing_error_code", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_webhook_inbox_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_inbox")),
        sa.UniqueConstraint(
            "merchant_id", "provider", "provider_event_id", name="webhook_provider_event"
        ),
    )
    op.create_index(
        op.f("ix_webhook_inbox_merchant_id"), "webhook_inbox", ["merchant_id"], unique=False
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.String(length=64), nullable=False),
        sa.Column("provider_subscription_id", sa.String(length=128), nullable=False),
        sa.Column("plan_name", sa.String(length=200), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "subscription_state",
            sa.Enum(
                "UNKNOWN",
                "CREATED",
                "AUTHENTICATED",
                "ACTIVE",
                "PENDING",
                "HALTED",
                "PAUSED",
                "CANCELLED",
                "COMPLETED",
                name="subscription_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("current_billing_cycle_key", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_paise >= 0", name=op.f("ck_subscriptions_subscription_amount_nonnegative")
        ),
        sa.CheckConstraint(
            "length(currency) = 3", name=op.f("ck_subscriptions_subscription_currency_length")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_subscriptions_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_subscriptions_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint(
            "merchant_id", "provider_subscription_id", name="subscription_merchant_provider"
        ),
    )
    op.create_index(
        op.f("ix_subscriptions_customer_id"), "subscriptions", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_subscriptions_merchant_id"), "subscriptions", ["merchant_id"], unique=False
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("subscription_id", sa.String(length=64), nullable=False),
        sa.Column("provider_invoice_id", sa.String(length=128), nullable=False),
        sa.Column("billing_cycle_key", sa.String(length=64), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("amount_paid_paise", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("invoice_state", sa.String(length=32), nullable=False),
        sa.Column(
            "due_at", services.api.app.models.entities.UTCDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "created_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_paid_paise <= amount_paise", name=op.f("ck_invoices_invoice_paid_lte_amount")
        ),
        sa.CheckConstraint(
            "amount_paid_paise >= 0", name=op.f("ck_invoices_invoice_paid_nonnegative")
        ),
        sa.CheckConstraint(
            "amount_paise >= 0", name=op.f("ck_invoices_invoice_amount_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_invoices_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_invoices_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("merchant_id", "provider_invoice_id", name="invoice_merchant_provider"),
        sa.UniqueConstraint(
            "merchant_id", "subscription_id", "billing_cycle_key", name="invoice_billing_cycle"
        ),
    )
    op.create_index(op.f("ix_invoices_merchant_id"), "invoices", ["merchant_id"], unique=False)
    op.create_index(
        op.f("ix_invoices_subscription_id"), "invoices", ["subscription_id"], unique=False
    )
    op.create_table(
        "payment_attempts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("invoice_id", sa.String(length=64), nullable=False),
        sa.Column("subscription_id", sa.String(length=64), nullable=False),
        sa.Column("provider_payment_id", sa.String(length=128), nullable=True),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "payment_state",
            sa.Enum(
                "UNKNOWN",
                "FAILED",
                "PENDING",
                "AUTHORIZED",
                "CAPTURED",
                "REFUNDED",
                name="payment_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("method", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_source", sa.String(length=64), nullable=True),
        sa.Column("error_step", sa.String(length=64), nullable=True),
        sa.Column("error_reason", sa.String(length=128), nullable=True),
        sa.Column(
            "occurred_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_paise >= 0", name=op.f("ck_payment_attempts_payment_attempt_amount_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_payment_attempts_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_payment_attempts_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_payment_attempts_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_attempts")),
        sa.UniqueConstraint(
            "merchant_id", "provider_payment_id", name="payment_attempt_merchant_provider"
        ),
    )
    op.create_index(
        op.f("ix_payment_attempts_invoice_id"), "payment_attempts", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_attempts_merchant_id"), "payment_attempts", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_attempts_subscription_id"),
        "payment_attempts",
        ["subscription_id"],
        unique=False,
    )
    op.create_table(
        "recovery_cases",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.String(length=64), nullable=False),
        sa.Column("subscription_id", sa.String(length=64), nullable=False),
        sa.Column("failed_invoice_id", sa.String(length=64), nullable=True),
        sa.Column("billing_cycle_key", sa.String(length=64), nullable=True),
        sa.Column("failed_payment_id", sa.String(length=64), nullable=True),
        sa.Column(
            "case_outcome",
            sa.Enum(
                "OPEN",
                "RECOVERED",
                "PARTIALLY_RECOVERED",
                "ESCALATED",
                "DISPUTED",
                "STOPPED",
                "EXPIRED",
                name="case_outcome",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_state",
            sa.Enum(
                "UNKNOWN",
                "FAILED",
                "PENDING",
                "AUTHORIZED",
                "CAPTURED",
                "REFUNDED",
                name="case_payment_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "subscription_state",
            sa.Enum(
                "UNKNOWN",
                "CREATED",
                "AUTHENTICATED",
                "ACTIVE",
                "PENDING",
                "HALTED",
                "PAUSED",
                "CANCELLED",
                "COMPLETED",
                name="case_subscription_state",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "contact_disposition",
            sa.Enum(
                "NOT_CONTACTED",
                "CONTACT_SCHEDULED",
                "NO_ANSWER",
                "BUSY",
                "ENGAGED",
                "PROMISE_TO_PAY",
                "OPTED_OUT",
                "WRONG_PERSON",
                "DISPUTE",
                "ALREADY_PAID",
                name="contact_disposition",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "revenue_attribution",
            sa.Enum(
                "NONE",
                "SIMULATED",
                "RAZORPAY_TEST_VERIFIED",
                "VERIFIED_EXTERNAL",
                name="revenue_attribution",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "diagnosis",
            sa.Enum(
                "TRANSIENT_RETRYABLE",
                "INSUFFICIENT_FUNDS",
                "AUTHENTICATION_REQUIRED",
                "INSTRUMENT_INVALID",
                "MERCHANT_ERROR",
                "RISK_OR_COMPLIANCE_BLOCK",
                "UNKNOWN",
                name="diagnosis",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("amount_at_risk_paise", sa.BigInteger(), nullable=False),
        sa.Column("arrears_collected_paise", sa.BigInteger(), nullable=False),
        sa.Column("case_recovered", sa.Boolean(), nullable=False),
        sa.Column("subscription_reactivated", sa.Boolean(), nullable=False),
        sa.Column(
            "opened_at", services.api.app.models.entities.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "recovery_deadline",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "recovered_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "amount_at_risk_paise >= 0", name=op.f("ck_recovery_cases_case_risk_nonnegative")
        ),
        sa.CheckConstraint(
            "arrears_collected_paise >= 0",
            name=op.f("ck_recovery_cases_case_collected_nonnegative"),
        ),
        sa.CheckConstraint(
            "failed_invoice_id IS NOT NULL OR billing_cycle_key IS NOT NULL",
            name=op.f("ck_recovery_cases_case_has_invoice_or_cycle"),
        ),
        sa.CheckConstraint(
            "recovery_deadline > opened_at", name=op.f("ck_recovery_cases_case_deadline_after_open")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_recovery_cases_case_version_positive")),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
            name=op.f("fk_recovery_cases_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["failed_invoice_id"],
            ["invoices.id"],
            name=op.f("fk_recovery_cases_failed_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["failed_payment_id"],
            ["payment_attempts.id"],
            name=op.f("fk_recovery_cases_failed_payment_id_payment_attempts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_recovery_cases_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_recovery_cases_subscription_id_subscriptions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_cases")),
        sa.UniqueConstraint("merchant_id", "failed_invoice_id", name="case_failed_invoice"),
    )
    op.create_index(
        op.f("ix_recovery_cases_customer_id"), "recovery_cases", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_recovery_cases_failed_invoice_id"),
        "recovery_cases",
        ["failed_invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recovery_cases_merchant_id"), "recovery_cases", ["merchant_id"], unique=False
    )
    op.create_index(
        "ix_recovery_cases_outcome_opened",
        "recovery_cases",
        ["case_outcome", "opened_at", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recovery_cases_subscription_id"),
        "recovery_cases",
        ["subscription_id"],
        unique=False,
    )
    op.create_index(
        "uq_recovery_cases_fallback_cycle",
        "recovery_cases",
        ["merchant_id", "billing_cycle_key"],
        unique=True,
        postgresql_where=sa.text("failed_invoice_id IS NULL"),
        sqlite_where=sa.text("failed_invoice_id IS NULL"),
    )
    op.create_table(
        "recovery_actions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum(
                "WAIT_FOR_GATEWAY_RETRY",
                "OPEN_CUSTOMER_PAYMENT_SURFACE",
                "START_VOICE",
                "SEND_TO_CUSTOMER_AGENT",
                "ESCALATE_TO_HUMAN",
                "STOP",
                name="recovery_action_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_surface_type",
            sa.Enum(
                "SUBSCRIPTION_CARD_UPDATE",
                "SUBSCRIPTION_INVOICE_LINK",
                "STANDARD_PAYMENT_LINK",
                name="payment_surface_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PROPOSED",
                "AWAITING_APPROVAL",
                "SCHEDULED",
                "EXECUTING",
                "SUCCEEDED",
                "FAILED",
                "CANCELLED",
                name="action_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column(
            "scheduled_for",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("external_reference", sa.String(length=256), nullable=True),
        sa.Column("customer_url", sa.Text(), nullable=True),
        sa.Column(
            "completed_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(action_type = 'OPEN_CUSTOMER_PAYMENT_SURFACE' AND "
            "payment_surface_type IS NOT NULL) OR "
            "(action_type <> 'OPEN_CUSTOMER_PAYMENT_SURFACE' AND "
            "payment_surface_type IS NULL)",
            name=op.f("ck_recovery_actions_action_surface_matches_type"),
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["recovery_cases.id"],
            name=op.f("fk_recovery_actions_case_id_recovery_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_actions")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_recovery_actions_idempotency_key")),
    )
    op.create_index(
        op.f("ix_recovery_actions_case_id"), "recovery_actions", ["case_id"], unique=False
    )
    op.create_table(
        "recovery_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column(
            "evidence_kind",
            sa.Enum(
                "SIMULATED",
                "RAZORPAY_TEST_VERIFIED",
                name="evidence_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "occurred_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "recorded_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column("source_event_id", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["recovery_cases.id"],
            name=op.f("fk_recovery_events_case_id_recovery_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_events")),
        sa.UniqueConstraint("case_id", "source_event_id", name="event_case_source_event"),
    )
    op.create_index(
        op.f("ix_recovery_events_case_id"), "recovery_events", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_recovery_events_correlation_id"),
        "recovery_events",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        "ix_recovery_events_timeline",
        "recovery_events",
        ["case_id", "occurred_at", "recorded_at", "id"],
        unique=False,
    )
    op.create_table(
        "revenue_recognition",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("payment_attempt_id", sa.String(length=64), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_event_id", sa.String(length=200), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column(
            "attribution",
            sa.Enum(
                "NONE",
                "SIMULATED",
                "RAZORPAY_TEST_VERIFIED",
                "VERIFIED_EXTERNAL",
                name="recognition_attribution",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("arrears_collected", sa.Boolean(), nullable=False),
        sa.Column("subscription_reactivated", sa.Boolean(), nullable=False),
        sa.Column(
            "recognized_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attribution <> 'NONE'", name=op.f("ck_revenue_recognition_revenue_has_attribution")
        ),
        sa.CheckConstraint(
            "amount_paise > 0", name=op.f("ck_revenue_recognition_revenue_amount_positive")
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["recovery_cases.id"],
            name=op.f("fk_revenue_recognition_case_id_recovery_cases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_revenue_recognition_merchant_id_merchants"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["payment_attempt_id"],
            ["payment_attempts.id"],
            name=op.f("fk_revenue_recognition_payment_attempt_id_payment_attempts"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_revenue_recognition")),
        sa.UniqueConstraint(
            "merchant_id", "provider", "provider_event_id", name="revenue_provider_event"
        ),
    )
    op.create_index(
        op.f("ix_revenue_recognition_case_id"), "revenue_recognition", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_revenue_recognition_merchant_id"),
        "revenue_recognition",
        ["merchant_id"],
        unique=False,
    )
    op.create_table(
        "policy_decisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=64), nullable=False),
        sa.Column("action_id", sa.String(length=64), nullable=True),
        sa.Column(
            "disposition",
            sa.Enum(
                "ALLOW",
                "BLOCK",
                "DELAY",
                "REQUIRE_MANUAL_APPROVAL",
                name="policy_disposition",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("decision_code", sa.String(length=128), nullable=False),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column(
            "delay_until",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            services.api.app.models.entities.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(disposition = 'DELAY' AND delay_until IS NOT NULL) OR "
            "(disposition <> 'DELAY' AND delay_until IS NULL)",
            name=op.f("ck_policy_decisions_policy_delay_timestamp"),
        ),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["recovery_actions.id"],
            name=op.f("fk_policy_decisions_action_id_recovery_actions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["recovery_cases.id"],
            name=op.f("fk_policy_decisions_case_id_recovery_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_decisions")),
    )
    op.create_index(
        op.f("ix_policy_decisions_action_id"), "policy_decisions", ["action_id"], unique=False
    )
    op.create_index(
        op.f("ix_policy_decisions_case_id"), "policy_decisions", ["case_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_policy_decisions_case_id"), table_name="policy_decisions")
    op.drop_index(op.f("ix_policy_decisions_action_id"), table_name="policy_decisions")
    op.drop_table("policy_decisions")
    op.drop_index(op.f("ix_revenue_recognition_merchant_id"), table_name="revenue_recognition")
    op.drop_index(op.f("ix_revenue_recognition_case_id"), table_name="revenue_recognition")
    op.drop_table("revenue_recognition")
    op.drop_index("ix_recovery_events_timeline", table_name="recovery_events")
    op.drop_index(op.f("ix_recovery_events_correlation_id"), table_name="recovery_events")
    op.drop_index(op.f("ix_recovery_events_case_id"), table_name="recovery_events")
    op.drop_table("recovery_events")
    op.drop_index(op.f("ix_recovery_actions_case_id"), table_name="recovery_actions")
    op.drop_table("recovery_actions")
    op.drop_index(
        "uq_recovery_cases_fallback_cycle",
        table_name="recovery_cases",
        postgresql_where=sa.text("failed_invoice_id IS NULL"),
        sqlite_where=sa.text("failed_invoice_id IS NULL"),
    )
    op.drop_index(op.f("ix_recovery_cases_subscription_id"), table_name="recovery_cases")
    op.drop_index("ix_recovery_cases_outcome_opened", table_name="recovery_cases")
    op.drop_index(op.f("ix_recovery_cases_merchant_id"), table_name="recovery_cases")
    op.drop_index(op.f("ix_recovery_cases_failed_invoice_id"), table_name="recovery_cases")
    op.drop_index(op.f("ix_recovery_cases_customer_id"), table_name="recovery_cases")
    op.drop_table("recovery_cases")
    op.drop_index(op.f("ix_payment_attempts_subscription_id"), table_name="payment_attempts")
    op.drop_index(op.f("ix_payment_attempts_merchant_id"), table_name="payment_attempts")
    op.drop_index(op.f("ix_payment_attempts_invoice_id"), table_name="payment_attempts")
    op.drop_table("payment_attempts")
    op.drop_index(op.f("ix_invoices_subscription_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_merchant_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_subscriptions_merchant_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_customer_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_webhook_inbox_merchant_id"), table_name="webhook_inbox")
    op.drop_table("webhook_inbox")
    op.drop_index(op.f("ix_customers_merchant_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index("ix_outbox_unpublished", table_name="outbox_messages")
    op.drop_index(op.f("ix_outbox_messages_aggregate_id"), table_name="outbox_messages")
    op.drop_table("outbox_messages")
    op.drop_table("merchants")
    # ### end Alembic commands ###
