"""add merchant policy settings

Revision ID: 77dabad16ba0
Revises: 61d778a7486b
Create Date: 2026-08-27 21:04:10.018707
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from services.api.app.models.entities import UTCDateTime

revision: str = "77dabad16ba0"
down_revision: str | None = "61d778a7486b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant_policy_settings",
        sa.Column("merchant_id", sa.String(length=64), nullable=False),
        sa.Column("quiet_hours_start", sa.String(length=5), nullable=True),
        sa.Column("quiet_hours_end", sa.String(length=5), nullable=True),
        sa.Column("max_contacts_per_7_days", sa.Integer(), nullable=True),
        sa.Column("require_approval_above_paise", sa.BigInteger(), nullable=True),
        sa.Column("require_approval_actions", sa.JSON(), nullable=False),
        sa.Column("recovery_kill_switch", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(quiet_hours_start IS NULL) = (quiet_hours_end IS NULL)",
            name=op.f("ck_merchant_policy_settings_policy_quiet_pair"),
        ),
        sa.CheckConstraint(
            "max_contacts_per_7_days IS NULL OR max_contacts_per_7_days > 0",
            name=op.f("ck_merchant_policy_settings_policy_contact_limit_positive"),
        ),
        sa.CheckConstraint(
            "require_approval_above_paise IS NULL OR require_approval_above_paise >= 0",
            name=op.f("ck_merchant_policy_settings_approval_threshold_nonnegative"),
        ),
        sa.CheckConstraint(
            "version >= 1",
            name=op.f("ck_merchant_policy_settings_policy_settings_version_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_merchant_policy_settings_merchant_id_merchants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("merchant_id", name=op.f("pk_merchant_policy_settings")),
    )
    op.execute(
        sa.text(
            """
            INSERT INTO merchant_policy_settings (
                merchant_id,
                quiet_hours_start,
                quiet_hours_end,
                max_contacts_per_7_days,
                require_approval_above_paise,
                require_approval_actions,
                recovery_kill_switch,
                version,
                created_at,
                updated_at
            )
            SELECT
                id,
                '20:00',
                '09:00',
                2,
                500000,
                CAST('[]' AS JSON),
                false,
                1,
                CURRENT_TIMESTAMP,
                CURRENT_TIMESTAMP
            FROM merchants
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("merchant_policy_settings")
    # ### end Alembic commands ###
